name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 8
          cache: "gradle"
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build
        run: chmod +x ./gradlew && ./gradlew setupCiWorkspace && ./gradlew build 
      - name: Upload artifact
        run: |
          cd build/libs
          export JAR=$(find . -regex '.*FDPClient-[0-9|.]*\.jar')
          export C_VERSION=$(echo $JAR | sed -r 's/.*\/FDPClient-([a-zA-Z][0-9]+)\.jar/\1/')
          export MINECRAFT_VERSION='1.8.9'
          echo Client Version: $C_VERSION, Minecraft: $MINECRAFT_VERSION
          zip -r fdpclient.zip $JAR
          md5sum fdpclient.zip
          curl --connect-timeout 30 -m 300 -X POST -F "artifact=@fdpclient.zip" -H "Authorization: ${{ secrets.NIGHTLY_PASS }}" -F "gh_id=${{ github.event.head_commit.id }}" -F "gh_ref=${{ github.ref }}" -F "gh_message=${{ github.event.head_commit.message }}" -F "gh_timestamp=${{ github.event.head_commit.timestamp }}" -F "lb_version=$C_VERSION" -F "mc_version=$MINECRAFT_VERSION" -F "jre_version=8" -F "subsystem=forge" https://api.liquidbounce.net/api/v1/version/new
      - name: Rename build artifacts
        run: mv build/libs/FDPClient-*.jar build/libs/FDPClient-build.jar
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: FDPClient
          path: build/libs/FDPClient-build.jar
